//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCuenta
    {
        public tblCuenta()
        {
            this.tblMovimiento = new HashSet<tblMovimiento>();
        }
    
        public int id_cuenta { get; set; }
        public int numeroCuenta { get; set; }
        public int id_cliente { get; set; }
        public int id_tipoCuenta { get; set; }
        public int id_moneda { get; set; }
        public double saldo { get; set; }
        public int estado { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblMoneda tblMoneda { get; set; }
        public virtual tblTipoCuenta tblTipoCuenta { get; set; }
        public virtual ICollection<tblMovimiento> tblMovimiento { get; set; }
    }
}
