//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCuenta
    {
        public tblCuenta()
        {
            this.tblMovimiento = new HashSet<tblMovimiento>();
            this.tblTransferencia = new HashSet<tblTransferencia>();
            this.tblTransferencia1 = new HashSet<tblTransferencia>();
        }
    
        public int id_cuenta { get; set; }
        public int numeroCuenta { get; set; }
        public int id_cliente { get; set; }
        public int id_tipoCuenta { get; set; }
        public int id_moneda { get; set; }
        public double saldo { get; set; }
        public int estado { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        public virtual tblMoneda tblMoneda { get; set; }
        public virtual tblTipoCuenta tblTipoCuenta { get; set; }
        public virtual ICollection<tblMovimiento> tblMovimiento { get; set; }
        public virtual ICollection<tblTransferencia> tblTransferencia { get; set; }
        public virtual ICollection<tblTransferencia> tblTransferencia1 { get; set; }
    }
}
