//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinicioSesion
    {
        public int id_inicioSesion { get; set; }
        public string usuario { get; set; }
        public int contraseña { get; set; }
        public System.DateTime ultimoIngreso { get; set; }
        public int id_tipoUsuario { get; set; }
    
        public virtual tblTipoUsuario tblTipoUsuario { get; set; }
    }
}
