//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovimiento
    {
        public int id_movimiento { get; set; }
        public double monto { get; set; }
        public System.DateTime fechaDelMovimiento { get; set; }
        public int id_cuenta { get; set; }
        public int id_tipoMovimiento { get; set; }
    
        public virtual tblCuenta tblCuenta { get; set; }
        public virtual tblTipoMovimiento tblTipoMovimiento { get; set; }
    }
}
