//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMoneda
    {
        public tblMoneda()
        {
            this.tblCuenta = new HashSet<tblCuenta>();
        }
    
        public int id_moneda { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public double tipoCambio { get; set; }
    
        public virtual ICollection<tblCuenta> tblCuenta { get; set; }
    }
}
