//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoCuenta
    {
        public tblTipoCuenta()
        {
            this.tblCuenta = new HashSet<tblCuenta>();
        }
    
        public int id_tipoCuenta { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
    
        public virtual ICollection<tblCuenta> tblCuenta { get; set; }
    }
}
