//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoUsuario
    {
        public tblTipoUsuario()
        {
            this.tblinicioSesion = new HashSet<tblinicioSesion>();
        }
    
        public int id_tipoUsuario { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<tblinicioSesion> tblinicioSesion { get; set; }
    }
}
