//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Ejemplo
    {
        public string nombre { get; set; }
        public int id_cliente { get; set; }
        public string nombreCliente { get; set; }
        public string segundoApellido { get; set; }
        public string primerApellido { get; set; }
    }
}
